### ISSUE TITLE
SQL error occurs in the CustomerEvaluation route

### ISSUE THREAD

**Issue by jonmwalton** [jbossdemocentral/jboss-fuse-homeloan#12]
The demo deploys and starts up fine, however when you drop the data files into the appropriate directory a SQL error occurs in the CustomerEvaluation route:

Failed delivery for (MessageId: queue_customer_ID_Jons-Work-MacBook.local-50433-1448273339430-1_1_1_1_1 on ExchangeId: ID-Jons-Work-MacBook-local-50258-1448273150019-0-1). Exhausted after delivery attempt: 1 caught: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar []; nested exception is org.h2.jdbc.JdbcSQLException: Table "CUSTINFO" not found; SQL statement:
delete from CustInfo where nationalID = ?; [42102-181]
## Message History

RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[CustomerEvaluation] [CustomerEvaluation] [activemq://queue:customer                                                     ] [       414]
[CustomerEvaluation] [to3               ] [ref:toCustInfo                                                                ] [        97]
[CustomerEvaluation] [log1              ] [log                                                                           ] [        13]
[CustomerEvaluation] [to4               ] [sql:{{sql.deleteCustInfo}}?alwaysPopulateStatement=true                       ] [       301]
## Exchange

Exchange[
    Id                  ID-Jons-Work-MacBook-local-50258-1448273150019-0-1
    ExchangePattern     InOnly
    Headers             {breadcrumbId=ID-Jons-Work-MacBook-local-50238-1448273140576-0-1, CamelFileAbsolute=false, CamelFileAbsolutePath=/Users/jonwalton/Documents/RedHat/Fuse/jboss-fuse-homeloan-master/target/jboss-fuse-6.2.0.redhat-133/instances/datarecievercon/datafile/homeloancust-2.xml, CamelFileLastModified=1440537330000, CamelFileLength=229, CamelFileName=homeloancust-2.xml, CamelFileNameConsumed=homeloancust-2.xml, CamelFileNameOnly=homeloancust-2.xml, CamelFileParent=datafile, CamelFilePath=datafile/homeloancust-2.xml, CamelFileRelativePath=homeloancust-2.xml, CamelRedelivered=false, CamelRedeliveryCounter=0, JMSCorrelationID=null, JMSDeliveryMode=2, JMSDestination=queue://customer, JMSExpiration=0, JMSMessageID=ID:Jons-Work-MacBook.local-50433-1448273339430-1:1:1:1:1, JMSPriority=4, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1448273339568, JMSType=null, JMSXGroupID=null, JMSXUserID=null}
    BodyType            org.blogdemo.homeloan.model.CustInfo
    Body                org.blogdemo.homeloan.model.CustInfo@430ea6e2
]

**Comment by alberttwong** [comment]
I was able to verify that this error.   Christina will have to fix it since it was before my time.

**Comment by weimeilin79** [comment]
Fixed!
