### ISSUE TITLE
Request - Option to create the demo on OpenShift Online

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-homeloan#2]
Just a request.   Is it possible to create this demo via OpenShift Online (ease of use for people).

**Comment by weimeilin79** [comment]
I don't have time for this yet, I still have several demos to migrate from 6.1 to 6.2. If you would like to contribute, let me know, I can let you have access to all my demos. :)

**Comment by alberttwong** [comment]
Let me test the demos and afterwards when I have time, I'd like to get help.

**Comment by weimeilin79** [comment]
OpenShift will not support Blueprint. So this demo will not go on OpenShift
