### ISSUE TITLE
Not sure what this demo is supposed to show.  Could use more context on how to run it. 

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-homeloan#3]
Not sure what this demo is supposed to show.  Could use more context on how to run it.

**Comment by weimeilin79** [comment]
This Demo is for getting started page on JBoss.org. I recently updated this demo the previous blogs are here: 
http://wei-meilin.blogspot.tw/2014/07/red-hat-jboss-fuse-getting-started-home.html
http://wei-meilin.blogspot.tw/2014/07/red-hat-jboss-fuse-getting-started-home_14.html
http://wei-meilin.blogspot.tw/2014/07/red-hat-jboss-fuse-getting-started-home_16.html
http://wei-meilin.blogspot.com/2014/07/red-hat-jboss-fuse-getting-started-home_16.html
http://wei-meilin.blogspot.com/2014/07/red-hat-jboss-fuse-getting-started-home_21.html
http://wei-meilin.blogspot.com/2014/07/red-hat-jboss-fuse-getting-started-home_22.html

The new video showing how to do it are here: 
Home Loan Part 1 - Camel, Folder to message queue, content switch
https://drive.google.com/open?id=0BwYg9EJiu13fS1p1Q29VdS04ZDA&authuser=0
Home Loan Part 2 - Camel, JDBC, SQL, Data Mapper
https://drive.google.com/open?id=0BwYg9EJiu13faGtmeXNKM25vRXc&authuser=0
Home Loan Part 3 - Camel, AMQ, HTTP4 with Google App Engine, Data Mapper
https://drive.google.com/open?id=0BwYg9EJiu13fbVNOejU2eEFjNFU&authuser=0
Home Loan Part 4 - Camel, JDBC, SQL, Data Mapper
https://drive.google.com/open?id=0BwYg9EJiu13fbGtvUG1sWXJJeG8&authuser=0
Home Loan Part 5 - Camel, Rest DSL, Restful Web Service
https://drive.google.com/open?id=0BwYg9EJiu13faDNQdTVRdXZTa28&authuser=0
Home Loan Part 6 - JBDS, Debugging
https://drive.google.com/open?id=0BwYg9EJiu13fMWI1bFY3SHZKbkk&authuser=0
Home Loan Part 7 - Fabric, Deploy, create container, Debugging
https://drive.google.com/open?id=0BwYg9EJiu13fekpwZDhuRl9JUXc&authuser=0

I just could not find time to write up blog about this demo yet.

**Comment by alberttwong** [comment]
I see new videos up at http://www.jboss.org/products/fuse/get-started/ that matches the source code.  The other links you referenced on blogspot don't seem to match up with the code in github.   Still, I enjoyed the older videos.  They seem to be more detailed and complete (see other ticket comment).

I plan on updating the README and education material more but I think I should wait until you get done with the updates.

**Comment by weimeilin79** [comment]
The Blog was my old fuse post, for 6.1, now I have done all 7 part of blog all updated to 6.2 with the new video. It's scheduled to publish twice a week, once all of them are out, will add the links to Readme.md.
