### ISSUE TITLE
Cannot easy download FUSE 6.2.0.124 from access.redhat.com

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-homeloan#4]
No obvious way to get it.  Request to upgrade to FUSE 6.2.0.133.

**Comment by alberttwong** [comment]
I'd do the upgrade myself but I was looking at the POM.xml file and it seems that there are a lot of changes you've done between projects and I don't know what is the "new" standard.

**Comment by weimeilin79** [comment]
I'll update it during weekend, been busy, stay tune

**Comment by weimeilin79** [comment]
Updated to JBoss Fuse 6.2.0 GA version
