### ISSUE TITLE
Error in init.sh - Profile homeloan-customerevaluation with version 1.0 does not exist.

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-homeloan#8]
Logging in as admin
317 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, c7:d1:4a:3a:69:f7:b6:76:9b:67:48:c3:08:d8:8f:19] presented unverified {} key: {}
Error executing command: Profile homeloan-customerevaluation with version 1.0 does not exist.
Add profile to container

**Comment by alberttwong** [comment]
Logging in as admin
308 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, c7:d1:4a:3a:69:f7:b6:76:9b:67:48:c3:08:d8:8f:19] presented unverified {} key: {}
Error executing command: Profile homeloan-houseappraisal with version 1.0 does not exist.
Add profile to container

Logging in as admin
309 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, c7:d1:4a:3a:69:f7:b6:76:9b:67:48:c3:08:d8:8f:19] presented unverified {} key: {}
Error executing command: Profile homeloan-summarywebapi with version 1.0 does not exist.

**Comment by weimeilin79** [comment]
can you plz pastes the entire init.sh output? Thanks!

**Comment by alberttwong** [comment]
Alberts-MacBook-Pro:jboss-fuse-homeloan alwong$ ./init.sh
#################################################################

## 

## Setting up the JBoss Fuse Getting Started Home Loan Demo

## 

## 

## #####  #   #  #####  #####

## #      #   #  #      #

## #####  #   #  #####  ####

## #      #   #      #  #

## #      #####  #####  #####

## 

## 

## 

## brought to you by,

## Christina Lin

## 

## 

#################################################################
Correct Maven version 3.2.3

JBoss Fuse Getting Started Home Loan Demo FUSE is present...
- creating the demo home directory...

Unpacking new JBoss FUSE...
- enabling demo accounts logins in users.properties file...
- enable camel counter in console in jmx.acl.whitelist.cfg  ...
- enable camel counter in console in jmx.acl.whitelist.properties  ...
- making sure 'FUSE' for server is executable...
- Start up Fuse in the background
- Create Fabric in Fuse

Logging in as admin
retrying (attempt 1) ...
retrying (attempt 2) ...
31546 [sshd-SshClient[5b0abc94]-nio2-thread-5] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
Waiting for container: root

It may take a couple of seconds for the container to provision...
You can use the --wait-for-provisioning option, if you want this command to block until the container is provisioned.
- Testing fabric,retry when not ready
  335 [sshd-SshClient[123f1134]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
  Go to Project directory

Start compile and deploy failover camel example project to fuse

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.blogdemo.homeloan:homeloan:1.0.0-SNAPSHOT (/Users/alwong/sandbox/jboss-fuse-homeloan/project/homeloan/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.fuse.bom:jboss-fuse-parent:pom:6.2.0.redhat-133 in http://maven.repository.redhat.com/techpreview/all was cached in the local repository, resolution will not be reattempted until the update interval of jboss-ga-repository has elapsed or updates are forced @ line 26, column 17 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Add profile to container

Logging in as admin
315 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
Error executing command: Profile homeloan-datareciever with version 1.0 does not exist.
Add profile to container

Logging in as admin
319 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
Error executing command: Profile homeloan-customerevaluation with version 1.0 does not exist.
Add profile to container

Logging in as admin
308 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
Error executing command: Profile homeloan-houseappraisal with version 1.0 does not exist.
Add profile to container

Logging in as admin
313 [sshd-SshClient[5b0abc94]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 19:22:aa:50:41:19:3c:8f:6e:6e:00:03:a4:61:c3:17] presented unverified {} key: {}
Error executing command: Profile homeloan-summarywebapi with version 1.0 does not exist.
To stop the backgroud Fuse process, please go to bin and execute stop

=#############################################################################################################=
=                                                                                                             =
=   Starting the camel route in JBoss Fuse as follows:                                                        =
=                                                                                                             =
=                                                                                                             =
=      - login to Fuse management console at:                                                                 =
=                                                                                                             =
=          http://localhost:8181    (u:admin/p:admin)                                                         =
=                                                                                                             =
=      - start home loan application, place the /support/data file to                                         =
=          target/jboss-fuse-6.2.0.redhat-133/instances/datarecievercon/datafile                              =
=          - homeloancust.xml                                                                                 =
=          - homeloancust-2.xml                                                                               =
=          - homeloanhouse.xml                                                                                =
=          - homeloanhouse-2.xml                                                                              =
=                                                                                                             =
=      - Take a look at through the Fuse Console                                                              =
=          -Camel routes in all containers                                                                    =
=          -Message Queue stats                                                                               =
=          -Web Registry                                                                                      =
=                                                                                                             =
=      - See the result of House Appraisal by accessing following URL                                         =
=                                                                                                             =
=         http://localhost:8185/homeloan/summaryservice/nationalID/A234567                                    =
=         http://localhost:8185/homeloan/summaryservice/nationalID/B56789                                     =
=                                                                                                             =
=      - once you are done, to stop and clean everything run                                                  =
=          ./clean.sh                                                                                         =
=                                                                                                             =
=#############################################################################################################=
Alberts-MacBook-Pro:jboss-fuse-homeloan alwong$

**Comment by weimeilin79** [comment]
Here is your problem: 
[ERROR] Non-resolvable import POM: Failure to find org.jboss.fuse.bom:jboss-fuse-parent:pom:6.2.0.redhat-133 in http://maven.repository.redhat.com/techpreview/all was cached in the local repository, resolution will not be reattempted until the update interval of jboss-ga-repository has elapsed or updates are forced @ line 26, column 17 -> [Help 2]

Check your maven repo. Make sure all jars are properly downloaded. Let me know the result and assign it back to me. Thanks

**Comment by alberttwong** [comment]
I'm still getting the same problem even when I clean out my repo.   I'm curious if someone else is having the same problem.

**Comment by weimeilin79** [comment]
And another thing, do you have fuse repo configure in your settings.xml? (I think that's why mine is working)
<id>release.fusesource.org</id>
<name>FuseSource Release Repository</name>
<url>http://repo.fusesource.com/nexus/content/repositories/releases</url>

Think that might be the problem, maybe not all people has their setting connected to fuse repo… I' have add it into the project pom.xml.

**Comment by alberttwong** [comment]
You got it right.   I'm missing pluginRepositories section in the pom.xml.   I'll update the pom.xml and submit.

**Comment by alberttwong** [comment]
got the new updates.  works great.
